version: 2.1
orbs:
  node: circleci/node@4.1.0
  aws-ecr: circleci/aws-ecr@6.15.0
jobs:
  test:
    executor:
      name: node/default
      tag: 14.15.1
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm test
          name: Run Mocha tests
      - store_artifacts:
          path: /tmp/test-results
          destination: raw-test-output
      - store_test_results:
          path: /tmp/test-results
  build-and-push:
    docker:
      - image: your_new_docker_image:tag
    steps:
      - checkout
      - aws-ecr/build-and-push-image:
          repo: slackcicd
          tag: "latest,v0.1.${CIRCLE_BUILD_NUM}"
          dockerfile: build/Dockerfile.prod
          path: .
          requires:
            - test
workflows:
  version: 2
  node-tests:
    jobs:
      - test
      - build-and-push:
          requires:
            - test
