version: 2.1
orbs:
  node: circleci/node@5.2.0
  aws-ecr: circleci/aws-ecr@9.1.0
jobs:
  test:
    executor:
      name: node/default
      tag: 14.15.1
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm test
          name: Run Mocha tests
      - store_artifacts:
          path: /tmp/test-results
          destination: raw-test-output
      - store_test_results:
          path: /tmp/test-results
  
  aws-ecr-build-and-push-image: # Define the job here
    docker:
      - image: circleci/node:14.15.1
    steps:
      - checkout
      - aws-ecr/build-and-push-image:
          repo: slackcicd
          tag: "latest,v0.1.${CIRCLE_BUILD_NUM}"
          dockerfile: build/Dockerfile.prod
          path: .
          requires:
            - test

workflows:
  node-tests:
    jobs:
      - test
      - aws-ecr-build-and-push-image: # Use the job here
          requires:
            - test

          

